using Content.Client.Message;
using Content.Shared._Sich.Nuke;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sich.Nuke;

[GenerateTypedNameReferences]
public sealed partial class MriyaRMCNuclearChargeWindow : DefaultWindow
{
    public event Action? OnStart;
    public event Action? OnAbort;

    public MriyaRMCNuclearChargeWindow()
    {
        RobustXamlLoader.Load(this);

        StartButton.OnPressed += _ => OnStart?.Invoke();
        AbortButton.OnPressed += _ => OnAbort?.Invoke();
    }

    public void SetState(MriyaRMCNuclearChargeBuiState state)
    {
        StatusLabel.SetMarkup(state.Status);
        StartButton.Disabled = !state.CanStart;
        AbortButton.Disabled = !state.CanAbort;
    }
}
